"""Echo Phase 4 — ingest Andy's Claude Code transcripts into the profile corpus.

Walks `~/.claude/projects/<project-id>/<session-id>.jsonl` for projects on
the whitelist, extracts user turns, and appends them to
`~/Documents/Luna Master/Andy Profile/claude-transcripts.md`. Dedupes by
session-id + line number via a sidecar file so re-runs are idempotent.

Whitelist semantics: opt-in by project-id. Andy edits
`Luna Master/Andy Profile/.transcript-whitelist.txt`. Default whitelist
includes only projects that are clearly Neural Bridge / personal AI work.
Work-confidential projects (corporate Azure tenants, etc.) are excluded
unless Andy adds them.

Filter rules:
- Only `type: queue-operation, operation: enqueue` lines (user turns)
- Skip empty content
- Skip system-injected wrappers (`<task-notification>`, `<system-reminder>`,
  `<ide_selection>`, `<local-command-stdout>`, `<command-...>`)
- Skip the standard "Caveat:" boilerplate that local-command sessions inject

Usage:
    python -m scripts.echo.ingest_claude_transcripts            # actual ingest
    python -m scripts.echo.ingest_claude_transcripts --dry-run  # plan only
    python -m scripts.echo.ingest_claude_transcripts --verbose  # log per-session counts

After it runs, Echo's next corpus pass will see the new content in
`claude-transcripts.md`.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

CLAUDE_PROJECTS_DIR = Path.home() / ".claude" / "projects"
VAULT_PROFILE_DIR = Path.home() / "Documents" / "Luna Master" / "Andy Profile"
WHITELIST_PATH = VAULT_PROFILE_DIR / ".transcript-whitelist.txt"
OUTPUT_PATH = VAULT_PROFILE_DIR / "claude-transcripts.md"
DEDUPE_SIDECAR = VAULT_PROFILE_DIR / ".transcript-ingested.txt"

# Projects on the default whitelist if no whitelist file exists yet.
DEFAULT_WHITELIST = [
    "-Users-andyherman-Desktop-Andy-Herman",
    "-Users-andyherman-Development-neural-bridge",
]

# Content prefixes that mark a system-injected message rather than an
# Andy-typed one. We skip these — they're not signal for style/voice analysis.
SYSTEM_PREFIXES = (
    "<task-notification>",
    "<system-reminder>",
    "<ide_selection>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<command-",
    "Caveat: The messages below were generated by the user while running local commands.",
    "<command-message>",
    "<bash-input>",
    "<bash-stdout>",
    "<bash-stderr>",
)

# Truncate any single user turn beyond this. Long pastes get marked.
MAX_CONTENT_CHARS = 6000


def load_whitelist() -> list[str]:
    """Load whitelist or seed it on first run."""
    if not WHITELIST_PATH.exists():
        VAULT_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
        seed = (
            "# Echo transcript-ingestion whitelist.\n"
            "# One project-id per line. Project-ids are the directory names under\n"
            "# ~/.claude/projects/ — they're cwd paths with / replaced by -.\n"
            "# Lines starting with # are comments. Add or remove as you like;\n"
            "# Echo only ingests transcripts from listed projects.\n"
            "#\n"
            "# Default whitelist (Neural Bridge + personal AI work):\n"
            + "\n".join(DEFAULT_WHITELIST)
            + "\n"
        )
        WHITELIST_PATH.write_text(seed, encoding="utf-8")
        print(f"seeded whitelist at {WHITELIST_PATH}", file=sys.stderr)

    lines = WHITELIST_PATH.read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def load_dedupe_sidecar() -> set[str]:
    """Load (session_id:line_no) keys we've already ingested."""
    if not DEDUPE_SIDECAR.exists():
        return set()
    return {
        line.strip()
        for line in DEDUPE_SIDECAR.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }


def save_dedupe_sidecar(seen: set[str]) -> None:
    VAULT_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
    DEDUPE_SIDECAR.write_text("\n".join(sorted(seen)) + "\n", encoding="utf-8")


def is_system_content(content: str) -> bool:
    """True if the content looks like a system-injected wrapper, not Andy's prose."""
    stripped = content.lstrip()
    return any(stripped.startswith(prefix) for prefix in SYSTEM_PREFIXES)


def truncate(text: str, limit: int = MAX_CONTENT_CHARS) -> str:
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…[content truncated]"


def find_jsonl_files(project_id: str) -> list[Path]:
    project_dir = CLAUDE_PROJECTS_DIR / project_id
    if not project_dir.is_dir():
        return []
    return sorted(project_dir.glob("*.jsonl"))


def extract_user_turns(jsonl_path: Path, project_id: str, seen: set[str]) -> list[dict]:
    """Yield user-turn records from a JSONL file. Skips already-seen and system-shaped lines."""
    out: list[dict] = []
    try:
        with jsonl_path.open("r", encoding="utf-8") as f:
            for lineno, line in enumerate(f, start=1):
                line = line.rstrip("\n")
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    continue

                if record.get("type") != "queue-operation":
                    continue
                if record.get("operation") != "enqueue":
                    continue

                content = record.get("content", "") or ""
                if not content.strip():
                    continue
                if is_system_content(content):
                    continue

                # Dedupe key uses the JSONL file's stem (its session-id-on-disk),
                # NOT the record's `sessionId` field. The record sometimes
                # references a parent/forwarded session ID that's shared across
                # multiple files, which would collide. (filename, lineno) is
                # guaranteed unique.
                file_session_id = jsonl_path.stem
                record_session_id = record.get("sessionId") or file_session_id
                key = f"{file_session_id}:{lineno}"
                if key in seen:
                    continue

                out.append({
                    "session_id": record_session_id,
                    "project_id": project_id,
                    "lineno": lineno,
                    "key": key,
                    "timestamp": record.get("timestamp", ""),
                    "content": content,
                })
    except (OSError, UnicodeDecodeError) as exc:
        print(f"  warn: skipping {jsonl_path.name} — {type(exc).__name__}: {exc}", file=sys.stderr)
    return out


def render_entry(turn: dict) -> str:
    """Markdown block for a single user turn."""
    ts = turn["timestamp"][:19] if turn["timestamp"] else "unknown"
    short_session = turn["session_id"][:8] if turn["session_id"] else "unknown"
    project_short = turn["project_id"].lstrip("-").replace("-", "/")
    content = truncate(turn["content"]).strip()
    return (
        f"\n### {ts}Z — claude session `{short_session}` (project: `{project_short}`)\n"
        f"<!-- key: {turn['key']} -->\n\n"
        f"> {content}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Ingest Claude transcripts into Echo's corpus.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Plan only — don't write to claude-transcripts.md or dedupe sidecar.")
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Per-session counts and progress.")
    args = parser.parse_args(argv)

    whitelist = load_whitelist()
    if not whitelist:
        print(f"error: whitelist at {WHITELIST_PATH} is empty. Add at least one project-id.", file=sys.stderr)
        return 1

    print(f"whitelist: {len(whitelist)} project(s)", file=sys.stderr)
    if args.verbose:
        for p in whitelist:
            print(f"  - {p}", file=sys.stderr)

    seen = load_dedupe_sidecar()
    print(f"dedupe sidecar: {len(seen)} previously-ingested keys", file=sys.stderr)

    new_turns: list[dict] = []
    for project_id in whitelist:
        files = find_jsonl_files(project_id)
        if not files:
            print(f"  skip {project_id}: no .jsonl files", file=sys.stderr)
            continue
        proj_count = 0
        for f in files:
            turns = extract_user_turns(f, project_id, seen)
            new_turns.extend(turns)
            proj_count += len(turns)
        if args.verbose:
            print(f"  {project_id}: {len(files)} files, {proj_count} new user turns", file=sys.stderr)

    print(f"total new user turns: {len(new_turns)}", file=sys.stderr)
    if not new_turns:
        print("nothing to ingest. exiting clean.", file=sys.stderr)
        return 0

    # Sort by timestamp ascending so the markdown file reads chronologically.
    new_turns.sort(key=lambda t: t.get("timestamp", ""))

    if args.dry_run:
        print(f"--dry-run: would append {len(new_turns)} entries to {OUTPUT_PATH}", file=sys.stderr)
        return 0

    VAULT_PROFILE_DIR.mkdir(parents=True, exist_ok=True)

    # Initialize the file with a header on first run.
    if not OUTPUT_PATH.exists():
        OUTPUT_PATH.write_text(
            "---\n"
            "type: corpus\n"
            "agent: echo\n"
            "source: claude-transcripts\n"
            f"created: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}\n"
            "---\n\n"
            "# Andy's Claude Code transcripts\n\n"
            "Append-only ingest of user turns from `~/.claude/projects/<project>/`. "
            "Whitelist-gated (see `.transcript-whitelist.txt`). System-injected wrappers "
            "(`<task-notification>`, `<system-reminder>`, etc.) are filtered out before append.\n\n"
            "Echo reads this on subsequent corpus passes alongside `raw-conversations.md` "
            "(Discord) and the vault content.\n",
            encoding="utf-8",
        )

    # Append all new turns.
    with OUTPUT_PATH.open("a", encoding="utf-8") as f:
        for turn in new_turns:
            f.write(render_entry(turn))
            seen.add(turn["key"])

    save_dedupe_sidecar(seen)

    print(f"✓ appended {len(new_turns)} entries to {OUTPUT_PATH.name}", file=sys.stderr)
    print(f"  dedupe sidecar now has {len(seen)} keys", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
