"""Echo — ingest Synapse SQLite journal entries into the profile corpus.

Reads `journal_entries` from Synapse's SQLite database and produces a single
verbatim-cited markdown corpus file at
`~/Documents/Luna Master/Andy Profile/synapse-journal.md`.

Each entry becomes a markdown block with the row's primary key as the citation,
its date and source as the header, its tags as a metadata line, and its content
as a blockquote (so it renders verbatim in Obsidian and reads as a quote to any
agent consuming it).

Idempotency model: full overwrite, deterministic output. The file's body is a
pure function of the rows in the DB, sorted by (created_at, id) ascending.
Re-running without new DB content produces byte-identical output, so Obsidian
and git see "no change". No sidecar required.

Scope (v1): journal_entries only. persona.json fields (writing_samples,
voice_phrases, voice registers) and the artifacts table are deliberately
out of scope until the corpus output proves useful.

Usage:
    python -m scripts.echo.ingest_synapse_db                # actual ingest
    python -m scripts.echo.ingest_synapse_db --dry-run      # plan only
    python -m scripts.echo.ingest_synapse_db --verbose      # log row counts
    python -m scripts.echo.ingest_synapse_db --db /alt/path # alt DB source

After it runs, Echo's next corpus pass will see the new content in
`synapse-journal.md`.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
from pathlib import Path

DEFAULT_DB_PATH = Path.home() / "Development" / "Synapse" / "data" / "agent_i.db"
VAULT_PROFILE_DIR = Path.home() / "Documents" / "Luna Master" / "Andy Profile"
OUTPUT_PATH = VAULT_PROFILE_DIR / "synapse-journal.md"


def resolve_db_path(arg_path: Path | None) -> Path:
    if arg_path is not None:
        return arg_path
    env_path = os.environ.get("SYNAPSE_DB_PATH")
    if env_path:
        return Path(env_path).expanduser()
    return DEFAULT_DB_PATH


def fetch_rows(db_path: Path) -> list[sqlite3.Row]:
    uri = f"file:{db_path}?mode=ro"
    conn = sqlite3.connect(uri, uri=True)
    conn.row_factory = sqlite3.Row
    try:
        cur = conn.execute(
            "SELECT id, date, created_at, content, tags, source, artifact_id "
            "FROM journal_entries "
            "ORDER BY created_at ASC, id ASC"
        )
        return list(cur)
    finally:
        conn.close()


def parse_tags(raw: str | None) -> list[str]:
    if not raw:
        return []
    try:
        value = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return []
    return [str(t) for t in value] if isinstance(value, list) else []


def render_entry(row: sqlite3.Row) -> str:
    src = row["source"] or "direct"
    lines: list[str] = []
    lines.append(f"## {row['date']} — {src} `{row['id']}`")
    tags = parse_tags(row["tags"])
    if tags:
        lines.append(f"**Tags:** {', '.join(tags)}")
    if row["artifact_id"]:
        lines.append(f"**Source artifact:** `{row['artifact_id']}`")
    lines.append("")
    content = row["content"] or ""
    for content_line in content.splitlines() or [""]:
        lines.append(f"> {content_line}".rstrip())
    lines.append("")
    return "\n".join(lines)


def render_corpus(rows: list[sqlite3.Row], db_path: Path) -> str:
    latest = rows[-1]["created_at"] if rows else ""
    home = str(Path.home())
    display_path = str(db_path).replace(home, "~", 1)

    out: list[str] = []
    out.append("---")
    out.append("type: corpus")
    out.append("agent: echo")
    out.append("source: synapse")
    out.append(f"source_db: {display_path}")
    out.append(f"entry_count: {len(rows)}")
    out.append(f"latest_entry: {latest}")
    out.append("---")
    out.append("")
    out.append("# Synapse journal corpus")
    out.append("")
    out.append(
        "Verbatim journal entries from Andy's career-intelligence app (Synapse). "
        "Generated by `scripts/echo/ingest_synapse_db.py` from "
        f"`{display_path}`. Do not edit by hand — re-run the ingester instead. "
        "Sorted oldest first to match `claude-transcripts.md`."
    )
    out.append("")
    for row in rows:
        out.append(render_entry(row))
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Ingest Synapse SQLite journal entries into Echo's corpus."
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=None,
        help="Path to Synapse agent_i.db (default: ~/Development/Synapse/data/agent_i.db, "
        "or $SYNAPSE_DB_PATH if set).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Read the DB and render, but don't write the output file.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print per-source row counts.",
    )
    args = parser.parse_args()

    db_path = resolve_db_path(args.db)
    if not db_path.exists():
        print(f"error: synapse db not found at {db_path}", file=sys.stderr)
        return 2

    rows = fetch_rows(db_path)
    if args.verbose:
        by_source: dict[str, int] = {}
        for r in rows:
            by_source[r["source"] or "direct"] = by_source.get(r["source"] or "direct", 0) + 1
        print(f"loaded {len(rows)} journal entries from {db_path}", file=sys.stderr)
        for src, n in sorted(by_source.items()):
            print(f"  {src}: {n}", file=sys.stderr)

    if not rows:
        print("no journal entries found; nothing to write. exiting clean.", file=sys.stderr)
        return 0

    body = render_corpus(rows, db_path)

    if args.dry_run:
        print(
            f"--dry-run: would write {len(body)} bytes "
            f"({len(rows)} entries) to {OUTPUT_PATH}",
            file=sys.stderr,
        )
        return 0

    VAULT_PROFILE_DIR.mkdir(parents=True, exist_ok=True)

    # Skip the write if the rendered body matches what's already on disk, so
    # Obsidian and git don't see spurious mtime/diff churn on no-op runs.
    if OUTPUT_PATH.exists() and OUTPUT_PATH.read_text(encoding="utf-8") == body:
        print(f"✓ no changes; {OUTPUT_PATH.name} already up to date ({len(rows)} entries)", file=sys.stderr)
        return 0

    OUTPUT_PATH.write_text(body, encoding="utf-8")
    print(f"✓ wrote {len(rows)} entries to {OUTPUT_PATH.name}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
