#!/bin/bash
# Set up a Cloudflare Tunnel exposing local Honcho at honcho.neural-bridge.dev.
#
# Prerequisites (steps that need YOUR browser, can't be automated):
#   1. `brew install cloudflared` (already done if you're running this)
#   2. `cloudflared tunnel login` (opens browser, authorize neural-bridge.dev zone)
#
# What this script does (idempotent, safe to re-run):
#   - Creates a named tunnel `honcho-bridge` (skips if already exists)
#   - Writes ~/.cloudflared/config.yml routing the hostname to localhost:8001
#   - Adds a DNS CNAME record for honcho.neural-bridge.dev
#   - Installs the launchd user agent so the tunnel auto-starts at login
#
# Companion doc: docs/HONCHO_COPILOT_PLAYBOOK.md

set -euo pipefail

TUNNEL_NAME="honcho-bridge"
HOSTNAME="honcho.neural-bridge.dev"
SERVICE="http://localhost:8001"
CLOUDFLARED_DIR="${HOME}/.cloudflared"
PLIST_LABEL="com.andyherman.neural-bridge.honcho-tunnel"
PLIST_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../launchd" && pwd)/${PLIST_LABEL}.plist"
PLIST_TARGET="${HOME}/Library/LaunchAgents/${PLIST_LABEL}.plist"
LOG_DIR="${HOME}/Library/Logs/neural-bridge"

# Pre-flight checks.
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "ERROR: cloudflared not installed. Run: brew install cloudflared" >&2
  exit 1
fi

if [[ ! -f "${CLOUDFLARED_DIR}/cert.pem" ]]; then
  echo "ERROR: ${CLOUDFLARED_DIR}/cert.pem missing." >&2
  echo "Run this first: cloudflared tunnel login" >&2
  exit 1
fi

if [[ ! -f "${PLIST_SOURCE}" ]]; then
  echo "ERROR: launchd plist source not found at ${PLIST_SOURCE}" >&2
  exit 1
fi

mkdir -p "${LOG_DIR}"

# 1. Create the tunnel (or use existing).
echo "Checking for existing tunnel '${TUNNEL_NAME}'..."
EXISTING_UUID="$(cloudflared tunnel list 2>/dev/null | awk -v name="${TUNNEL_NAME}" '$2==name {print $1}')"

if [[ -n "${EXISTING_UUID}" ]]; then
  echo "  Tunnel already exists: ${EXISTING_UUID}"
  TUNNEL_UUID="${EXISTING_UUID}"
else
  echo "  Creating tunnel..."
  cloudflared tunnel create "${TUNNEL_NAME}"
  TUNNEL_UUID="$(cloudflared tunnel list 2>/dev/null | awk -v name="${TUNNEL_NAME}" '$2==name {print $1}')"
  if [[ -z "${TUNNEL_UUID}" ]]; then
    echo "ERROR: could not resolve UUID for newly-created tunnel" >&2
    exit 1
  fi
  echo "  Created: ${TUNNEL_UUID}"
fi

CREDS_PATH="${CLOUDFLARED_DIR}/${TUNNEL_UUID}.json"
if [[ ! -f "${CREDS_PATH}" ]]; then
  echo "ERROR: tunnel credentials file missing at ${CREDS_PATH}" >&2
  echo "       cloudflared usually writes this on tunnel create." >&2
  exit 1
fi

# 2. Write the config.
CONFIG_PATH="${CLOUDFLARED_DIR}/config.yml"
echo "Writing ${CONFIG_PATH}..."
cat > "${CONFIG_PATH}" <<EOF
# Auto-generated by scripts/cloudflared/setup-honcho-tunnel.sh
# Re-running the setup script will overwrite this.
tunnel: ${TUNNEL_UUID}
credentials-file: ${CREDS_PATH}

ingress:
  - hostname: ${HOSTNAME}
    service: ${SERVICE}
    originRequest:
      noTLSVerify: false
      connectTimeout: 30s
  # Catch-all required by cloudflared.
  - service: http_status:404
EOF

# 3. Route DNS (idempotent — cloudflared rejects with a clear error if it exists).
echo "Routing DNS ${HOSTNAME} → ${TUNNEL_UUID}.cfargotunnel.com..."
if cloudflared tunnel route dns "${TUNNEL_NAME}" "${HOSTNAME}" 2>&1 | tee /tmp/cloudflared-route.log; then
  echo "  DNS route applied."
elif grep -q "already exists" /tmp/cloudflared-route.log; then
  echo "  DNS route already exists; continuing."
else
  echo "ERROR: DNS route failed. See /tmp/cloudflared-route.log" >&2
  exit 1
fi

# 4. Install the launchd plist.
echo "Installing launchd agent ${PLIST_LABEL}..."
cp "${PLIST_SOURCE}" "${PLIST_TARGET}"

if launchctl print "gui/$(id -u)/${PLIST_LABEL}" >/dev/null 2>&1; then
  echo "  Agent already loaded; reloading..."
  launchctl bootout "gui/$(id -u)/${PLIST_LABEL}" || true
  sleep 2
fi

launchctl bootstrap "gui/$(id -u)" "${PLIST_TARGET}"
sleep 3

if launchctl print "gui/$(id -u)/${PLIST_LABEL}" >/dev/null 2>&1; then
  echo "  Tunnel agent loaded and running."
else
  echo "  ERROR: tunnel agent did not load. Check ${LOG_DIR}/honcho-tunnel.stderr.log" >&2
  exit 1
fi

echo ""
echo "Done."
echo ""
echo "Verify with:"
echo "  curl -s https://${HOSTNAME}/openapi.json | head -5"
echo ""
echo "Next: put Cloudflare Access in front of the tunnel before going public."
echo "See docs/HONCHO_COPILOT_PLAYBOOK.md step 3."
